#!/opt/bin/php/bin/php
<?php
declare(strict_types=1);

$taskVendorPath = getenv('LAMBDA_TASK_ROOT') . '/vendor/autoload.php';
if(!file_exists($taskVendorPath)) {
    echo 'ERROR: There is no vendor dir in your task root! Please run composer install and deploy your function once again!';
    die(1);
}

/**
 * Include vendors.
 * This is ridiculously important as we do not include phuntime in custom runtime, this library should be delivered
 * in task depedencies.
 *
 * @noinspection PhpIncludeInspection
 */
require_once $taskVendorPath;

$runtime = \Phuntime\Aws\AwsRuntime::fromEnvironment();
$handler = \Phuntime\Core\Handler::fromRuntime($runtime);

try {
    $handler->boot();
} catch (\Throwable $exception) {
    $runtime->handleInitializationException($exception);
    return 1;
}

while (true) {
    $request = $runtime->getNextRequest();
    $handler->handleEvent($request);
}