#!/opt/bin/php
<?php
declare(strict_types=1);

use Phuntime\Core\PhpFpmProcess;

/**
 * @noinspection PhpIncludeInspection
 */
require_once __DIR__.'/vendor/autoload.php';

/**
 * FPM requests are handled by using Swoole Coroutine FastCGI Client
 * (@see https://www.swoole.co.uk/docs/modules/swoole-coroutine-fastcgi-client)
 * To make it work properly, we need to run our code in coroutine.
 */
Co\run(function() {
    $runtime = \Phuntime\Aws\AwsRuntime::fromEnvironment();
    $logger = $runtime->getLogger();
    $function = new \Phuntime\Core\FunctionHandler\FpmHandler($runtime->getContext(), $logger);
    $handler = \Phuntime\Core\EventProcessor::fromRuntime($runtime, $function);
    $fpmProcess = new PhpFpmProcess($logger, $_SERVER['FPM_PATH'] ?? '/opt/bin/php-fpm');

    try {
        $handler->boot();
        $fpmProcess->start();
    } catch (\Throwable $exception) {
        $runtime->handleInitializationException($exception);
        return 1;
    }

    /**
     * All events received by AWS Lambda are received and handled here.
     */
    while (true) {
        $request = $runtime->getNextRequest();
        $handler->handleEvent($request);
        $fpmProcess->tick();
    }

    return 1;
});